In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB

In [2]:
true = pd.read_csv("True.csv")
fake = pd.read_csv("Fake.csv")

In [3]:
true

title  \
0      As U.S. budget fight looms, Republicans flip t...   
1      U.S. military to accept transgender recruits o...   
2      Senior U.S. Republican senator: 'Let Mr. Muell...   
3      FBI Russia probe helped by Australian diplomat...   
4      Trump wants Postal Service to charge 'much mor...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text       subject  \
0      WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1      WASHINGTON (Reuters) - Transgender people will...  politicsNews   
2      WASHINGTON (Reuters) - The special counsel inv...  politicsNews   
3      WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews   
4      SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews   
...                                                  ...           ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...     worldnews   
21413  LONDON (Reuters) - LexisNexis, a provider of l...     worldnews   
21414  MINSK (Reuters) - In the shadow of disused Sov...     worldnews   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...     worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...     worldnews   

                     date  
0      December 31, 2017   
1      December 29, 2017   
2      December 31, 2017   
3      December 30, 2017   
4      December 29, 2017   
...                   ...  
21412    August 22, 2017   
21413    August 22, 2017   
21414    August 22, 2017   
21415    August 22, 2017   
21416    August 22, 2017   

[21417 rows x 4 columns]

In [5]:
fake

title  \
0       Donald Trump Sends Out Embarrassing New Year’...   
1       Drunk Bragging Trump Staffer Started Russian ...   
2       Sheriff David Clarke Becomes An Internet Joke...   
3       Trump Is So Obsessed He Even Has Obama’s Name...   
4       Pope Francis Just Called Out Donald Trump Dur...   
...                                                  ...   
23476  McPain: John McCain Furious That Iran Treated ...   
23477  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...   
23478  Sunnistan: US and Allied ‘Safe Zone’ Plan to T...   
23479  How to Blow $700 Million: Al Jazeera America F...   
23480  10 U.S. Navy Sailors Held by Iranian Military ...   

                                                    text      subject  \
0      Donald Trump just couldn t wish all Americans ...         News   
1      House Intelligence Committee Chairman Devin Nu...         News   
2      On Friday, it was revealed that former Milwauk...         News   
3      On Christmas day, Donald Trump announced that ...         News   
4      Pope Francis used his annual Christmas Day mes...         News   
...                                                  ...          ...   
23476  21st Century Wire says As 21WIRE reported earl...  Middle-east   
23477  21st Century Wire says It s a familiar theme. ...  Middle-east   
23478  Patrick Henningsen  21st Century WireRemember ...  Middle-east   
23479  21st Century Wire says Al Jazeera America will...  Middle-east   
23480  21st Century Wire says As 21WIRE predicted in ...  Middle-east   

                    date  
0      December 31, 2017  
1      December 31, 2017  
2      December 30, 2017  
3      December 29, 2017  
4      December 25, 2017  
...                  ...  
23476   January 16, 2016  
23477   January 16, 2016  
23478   January 15, 2016  
23479   January 14, 2016  
23480   January 12, 2016  

[23481 rows x 4 columns]

In [7]:
fake['target'] = 'fake'
true['target'] = 'true'

In [8]:
news = pd.concat([fake, true]).reset_index(drop = True)
news.head()

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   
2   Sheriff David Clarke Becomes An Internet Joke...   
3   Trump Is So Obsessed He Even Has Obama’s Name...   
4   Pope Francis Just Called Out Donald Trump Dur...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   
2  On Friday, it was revealed that former Milwauk...    News   
3  On Christmas day, Donald Trump announced that ...    News   
4  Pope Francis used his annual Christmas Day mes...    News   

                date target  
0  December 31, 2017   fake  
1  December 31, 2017   fake  
2  December 30, 2017   fake  
3  December 29, 2017   fake  
4  December 25, 2017   fake

In [10]:
fake.describe()

title   text subject  \
count                                               23481  23481   23481   
unique                                              17903  17455       6   
top     MEDIA IGNORES Time That Bill Clinton FIRED His...           News   
freq                                                    6    626    9050   

                date target  
count          23481  23481  
unique          1681      1  
top     May 10, 2017   fake  
freq              46  23481

In [11]:
true.describe()

title  \
count                                               21417   
unique                                              20826   
top     Factbox: Trump fills top jobs for his administ...   
freq                                                   14   

                                                     text       subject  \
count                                               21417         21417   
unique                                              21192             2   
top     (Reuters) - Highlights for U.S. President Dona...  politicsNews   
freq                                                    8         11272   

                      date target  
count                21417  21417  
unique                 716      1  
top     December 20, 2017    true  
freq                   182  21417

In [13]:
fake.columns

Index(['title', 'text', 'subject', 'date', 'target'], dtype='object')

In [14]:
fake['date'] = 'fake'
true['date'] = 'true'

In [16]:
fake
true

title  \
0      As U.S. budget fight looms, Republicans flip t...   
1      U.S. military to accept transgender recruits o...   
2      Senior U.S. Republican senator: 'Let Mr. Muell...   
3      FBI Russia probe helped by Australian diplomat...   
4      Trump wants Postal Service to charge 'much mor...   
...                                                  ...   
21412  'Fully committed' NATO backs new U.S. approach...   
21413  LexisNexis withdrew two products from Chinese ...   
21414  Minsk cultural hub becomes haven from authorities   
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text       subject  date  \
0      WASHINGTON (Reuters) - The head of a conservat...  politicsNews  true   
1      WASHINGTON (Reuters) - Transgender people will...  politicsNews  true   
2      WASHINGTON (Reuters) - The special counsel inv...  politicsNews  true   
3      WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews  true   
4      SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews  true   
...                                                  ...           ...   ...   
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...     worldnews  true   
21413  LONDON (Reuters) - LexisNexis, a provider of l...     worldnews  true   
21414  MINSK (Reuters) - In the shadow of disused Sov...     worldnews  true   
21415  MOSCOW (Reuters) - Vatican Secretary of State ...     worldnews  true   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...     worldnews  true   

      target  
0       true  
1       true  
2       true  
3       true  
4       true  
...      ...  
21412   true  
21413   true  
21414   true  
21415   true  
21416   true  

[21417 rows x 5 columns]

In [17]:
x_train,x_test,y_train,y_test = train_test_split(news['text'], news.target, test_size=0.2, random_state=1)

In [18]:
x_train

19625    Nothing says  Thanksgiving  or  family  like a...
21965    What this story shows is that while there are ...
36042    CAIRO (Reuters) - Russian President Vladimir P...
27618    WASHINGTON (Reuters) - President Donald Trump ...
25089    WASHINGTON (Reuters) - U.S. Senator John McCai...
                               ...                        
43723    GUATEMALA CITY (Reuters) - Guatemala s federal...
32511    WASHINGTON (Reuters) - U.S. House of Represent...
5192     While in Virginia, GOP presidential nominee Do...
12172    Judge Jeanine Pirro has had it with the left a...
33003    WASHINGTON (Reuters) - A congressional committ...
Name: text, Length: 35918, dtype: object

In [19]:
x_test

4528     Donald Trump is calling for one of the most co...
31727    WASHINGTON (Reuters) - Former Republican U.S. ...
10937    You re never to young to commit jihad Teachers...
13470    Laura Ingraham reminds the Never Trump people ...
40814    BERLIN/HANOVER (Reuters) - Germany s Social De...
                               ...                        
6053     On Thursday afternoon, Hillary Clinton deliver...
33584    ALBANY, New York,  (Reuters) - Governor Andrew...
29515    WASHINGTON (Reuters) - Commissioner Maureen Oh...
33415    WASHINGTON (Reuters) - The U.S. Senate Agricul...
35119    BEIRUT (Reuters) - Lebanon s interior minister...
Name: text, Length: 8980, dtype: object

In [20]:
y_train

19625    fake
21965    fake
36042    true
27618    true
25089    true
         ... 
43723    true
32511    true
5192     fake
12172    fake
33003    true
Name: target, Length: 35918, dtype: object

In [21]:
y_test

4528     fake
31727    true
10937    fake
13470    fake
40814    true
         ... 
6053     fake
33584    true
29515    true
33415    true
35119    true
Name: target, Length: 8980, dtype: object

In [22]:
pipe1 = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('model', LogisticRegression())])


In [23]:
pipe1

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('model', LogisticRegression())])

In [25]:
model_lr = pipe1.fit(x_train, y_train)
lr_pred = model_lr.predict(x_test)

print("Accuracy of Logistic Regression Classifier: {}%".format(round(accuracy_score(y_test, lr_pred)*100,2)))
print("\nConfusion Matrix of Logistic Regression Classifier:\n")
print(confusion_matrix(y_test, lr_pred))
print("\nCLassification Report of Logistic Regression Classifier:\n")
print(classification_report(y_test, lr_pred))


Accuracy of Logistic Regression Classifier: 98.73%

Confusion Matrix of Logistic Regression Classifier:

[[4617   65]
 [  49 4249]]

CLassification Report of Logistic Regression Classifier:

              precision    recall  f1-score   support

        fake       0.99      0.99      0.99      4682
        true       0.98      0.99      0.99      4298

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980



In [26]:
pipe2 = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('model', LinearSVC())])

model_svc = pipe2.fit(x_train, y_train)
svc_pred = model_svc.predict(x_test)

print("Accuracy of SVM Classifier: {}%".format(round(accuracy_score(y_test, svc_pred)*100,2)))
print("\nConfusion Matrix of SVM Classifier:\n")
print(confusion_matrix(y_test, svc_pred))
print("\nClassification Report of SVM Classifier:\n")
print(classification_report(y_test, svc_pred))


Accuracy of SVM Classifier: 99.39%

Confusion Matrix of SVM Classifier:

[[4644   38]
 [  17 4281]]

Classification Report of SVM Classifier:

              precision    recall  f1-score   support

        fake       1.00      0.99      0.99      4682
        true       0.99      1.00      0.99      4298

    accuracy                           0.99      8980
   macro avg       0.99      0.99      0.99      8980
weighted avg       0.99      0.99      0.99      8980



In [27]:
#Naive-Bayes classification
pipe3 = Pipeline([('vect', CountVectorizer()), ('tfidf', TfidfTransformer()), ('model', MultinomialNB())])

model_nb = pipe3.fit(x_train, y_train)
nb_pred = model_nb.predict(x_test)

print("Accuracy of Naive Bayes Classifier: {}%".format(round(accuracy_score(y_test, nb_pred)*100,2)))
print("\nConfusion Matrix of Naive Bayes Classifier:\n")
print(confusion_matrix(y_test, nb_pred))
print("\nClassification Report of Naive Bayes Classifier:\n")
print(classification_report(y_test, nb_pred))

Accuracy of Naive Bayes Classifier: 94.08%

Confusion Matrix of Naive Bayes Classifier:

[[4450  232]
 [ 300 3998]]

Classification Report of Naive Bayes Classifier:

              precision    recall  f1-score   support

        fake       0.94      0.95      0.94      4682
        true       0.95      0.93      0.94      4298

    accuracy                           0.94      8980
   macro avg       0.94      0.94      0.94      8980
weighted avg       0.94      0.94      0.94      8980

